base_model: mistralai/Mistral-7B-v0.1 
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizerFast
is_mistral_derived_model: true

load_in_8bit: true
load_in_4bit: false
strict: false

# note - we programmatically append this field to config 
# datasets: 
#   - path: mhenrichsen/alpaca_2k_test # TODO
#     type: alpaca # TODO
dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./lora-out 

adapter: lora
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: false
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: true
bf16: false
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 0.05
eval_table_size:
eval_table_max_new_tokens: 128
save_steps:
debug:
deepspeed:
weight_decay: 0.0

# fsdp:
#   - full_shard
#   - auto_wrap
# fsdp_config:
#   fsdp_offload_params: false
#   fsdp_state_dict_type: FULL_STATE_DICT
#   fsdp_transformer_layer_cls_to_wrap: MistralDecoderLayer


# torch_compile: true

special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"