name: Push to Replicate

on:
  push:
    branches:
      - main
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Select llama-2-7b
        run: make select model=llama-2-7b

      - name: Setup llama-2-7b Cog
        uses: replicate/setup-cog@v1.0.2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: |
          cog push r8.im/replicate-internal/ci-llama-2-7b

      - name: run basic prediction tests
        run: make test-ci-predict model=llama-2-7b
